//! Making changes outlast a reboot.
//!
//! Two different mechanisms, because the two kinds of setting live in two
//! different places:
//!
//!   * sysfs attributes belong to the kernel, so a udev rule can set them at
//!     device-add time and they survive suspend, resume and re-enumeration.
//!   * button maps and libinput properties belong to the X server, and udev
//!     cannot touch them. Those are written to a profile that `--restore`
//!     replays into a running session.

use std::fs;
use std::path::PathBuf;

use crate::error::{Error, Result};
use crate::sysfs::Node;

pub const UDEV_PATH: &str = "/etc/udev/rules.d/70-thinkpoint.rules";

#[derive(Debug, Clone)]
pub struct XSetting {
    pub device: String,
    /// Some(false) means the device was deliberately switched off.
    pub enabled: Option<bool>,
    pub button_map: Option<Vec<u8>>,
    pub props: Vec<(String, Vec<String>)>,
}

/// Render a udev rule that reapplies every non-default sysfs attribute.
///
/// `DRIVERS=="psmouse"` matches each PS/2 pointing device on the machine.
/// Assignments to attributes a given device does not have are skipped by udev
/// rather than failing the rule, so a touchpad sharing the bus is unharmed. The
/// commented variant narrows the match to one specific device by firmware id,
/// for machines where that matters.
pub fn udev_rule(nodes: &[Node], only_changed: bool) -> String {
    let mut out = String::new();
    out.push_str("# Generated by thinkpoint. Edit freely; it is not rewritten\n");
    out.push_str("# unless you save from the tool again.\n");
    out.push_str("#\n");
    out.push_str("# Reload with:  sudo udevadm control --reload\n");
    out.push_str("#               sudo udevadm trigger --subsystem-match=serio\n\n");

    let mut wrote_any = false;
    for node in nodes {
        let assignments: Vec<String> = node
            .attrs
            .iter()
            .filter(|a| !a.pending.is_empty() && (!only_changed || a.is_customised()))
            .map(|a| format!("ATTR{{{}}}=\"{}\"", a.name, a.pending))
            .collect();
        if assignments.is_empty() {
            continue;
        }
        wrote_any = true;

        if !node.description.is_empty() {
            out.push_str(&format!("# {}\n", node.description));
        }
        out.push_str(&format!(
            "ACTION==\"add\", SUBSYSTEM==\"serio\", DRIVERS==\"psmouse\", {}\n",
            assignments.join(", ")
        ));
        if !node.firmware_id.is_empty() {
            out.push_str(&format!(
                "# Narrower alternative, matching this device alone:\n\
                 # ACTION==\"add\", SUBSYSTEM==\"serio\", DRIVERS==\"psmouse\", \
                 ATTR{{firmware_id}}==\"{}\", {}\n",
                node.firmware_id,
                assignments.join(", ")
            ));
        }
        out.push('\n');
    }

    if !wrote_any {
        out.push_str(if only_changed {
            "# Nothing to persist: no sysfs attribute differs from its boot value.\n"
        } else {
            "# Nothing to persist: no tunable sysfs attributes were found.\n"
        });
    }
    out
}

pub fn profile_path() -> PathBuf {
    let base = std::env::var_os("XDG_CONFIG_HOME")
        .map(PathBuf::from)
        .or_else(|| std::env::var_os("HOME").map(|h| PathBuf::from(h).join(".config")))
        .unwrap_or_else(|| PathBuf::from("."));
    base.join("thinkpoint").join("profile.conf")
}

/// A deliberately dull line-based format: no parser dependency, and a user can
/// read or hand-edit it without reference to any documentation.
pub fn render_profile(settings: &[XSetting]) -> String {
    let mut out = String::new();
    out.push_str("# thinkpoint profile\n");
    out.push_str("# Replayed by:  thinkpoint --restore\n\n");
    for s in settings {
        if s.enabled.is_none() && s.button_map.is_none() && s.props.is_empty() {
            continue;
        }
        out.push_str(&format!("device = {}\n", s.device));
        if let Some(enabled) = s.enabled {
            out.push_str(&format!("enabled = {}\n", if enabled { 1 } else { 0 }));
        }
        if let Some(map) = &s.button_map {
            let joined: Vec<String> = map.iter().map(|b| b.to_string()).collect();
            out.push_str(&format!("button-map = {}\n", joined.join(" ")));
        }
        for (name, values) in &s.props {
            out.push_str(&format!("prop = {} = {}\n", name, values.join(" ")));
        }
        out.push('\n');
    }
    out
}

pub fn save_profile(settings: &[XSetting]) -> Result<PathBuf> {
    let path = profile_path();
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&path, render_profile(settings))?;
    Ok(path)
}

pub fn load_profile() -> Result<Vec<XSetting>> {
    let path = profile_path();
    let text =
        fs::read_to_string(&path).map_err(|e| Error::new(format!("{}: {e}", path.display())))?;

    let mut settings: Vec<XSetting> = Vec::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let Some((key, rest)) = line.split_once('=') else {
            continue;
        };
        let key = key.trim();
        let rest = rest.trim();

        match key {
            "device" => settings.push(XSetting {
                device: rest.to_string(),
                enabled: None,
                button_map: None,
                props: Vec::new(),
            }),
            "enabled" => {
                if let Some(current) = settings.last_mut() {
                    current.enabled = Some(rest != "0");
                }
            }
            "button-map" => {
                let Some(current) = settings.last_mut() else {
                    continue;
                };
                let map: std::result::Result<Vec<u8>, _> =
                    rest.split_whitespace().map(|t| t.parse::<u8>()).collect();
                current.button_map = map.ok();
            }
            "prop" => {
                let Some(current) = settings.last_mut() else {
                    continue;
                };
                let Some((name, values)) = rest.split_once('=') else {
                    continue;
                };
                current.props.push((
                    name.trim().to_string(),
                    values.split_whitespace().map(|s| s.to_string()).collect(),
                ));
            }
            _ => {}
        }
    }
    Ok(settings)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::sysfs::{Attr, AttrKind};
    use std::path::PathBuf;

    fn attr(name: &str, original: &str, pending: &str) -> Attr {
        Attr {
            name: name.to_string(),
            help: "",
            kind: AttrKind::Range(0, 255),
            value: original.to_string(),
            original: original.to_string(),
            pending: pending.to_string(),
            writable_directly: false,
            path: PathBuf::from("/sys/devices/platform/i8042/serio1").join(name),
        }
    }

    fn node(attrs: Vec<Attr>) -> Node {
        Node {
            path: PathBuf::from("/sys/devices/platform/i8042/serio1"),
            description: "i8042 AUX port".to_string(),
            firmware_id: "PNP: LEN0321 PNP0f13".to_string(),
            attrs,
        }
    }

    #[test]
    fn rule_carries_only_what_changed() {
        let n = node(vec![
            attr("sensitivity", "128", "90"),
            attr("resync_time", "0", "0"),
        ]);
        let rule = udev_rule(&[n], true);
        assert!(rule.contains("ATTR{sensitivity}=\"90\""));
        assert!(!rule.contains("resync_time"));
    }

    #[test]
    fn rule_says_so_when_nothing_changed() {
        let n = node(vec![attr("sensitivity", "128", "128")]);
        let rule = udev_rule(&[n], true);
        assert!(rule.contains("Nothing to persist"));
        assert!(!rule.contains("ACTION=="));
    }

    #[test]
    fn unfiltered_rule_carries_every_attribute() {
        let n = node(vec![
            attr("sensitivity", "128", "128"),
            attr("resync_time", "0", "0"),
        ]);
        let rule = udev_rule(&[n], false);
        assert!(rule.contains("ATTR{sensitivity}=\"128\""));
        assert!(rule.contains("ATTR{resync_time}=\"0\""));
    }

    #[test]
    fn rule_offers_a_device_specific_alternative() {
        let rule = udev_rule(&[node(vec![attr("sensitivity", "128", "90")])], true);
        assert!(rule.contains("# ACTION==\"add\""));
        assert!(rule.contains("ATTR{firmware_id}==\"PNP: LEN0321 PNP0f13\""));
    }

    #[test]
    fn profile_survives_a_round_trip() {
        let original = vec![XSetting {
            device: "TPPS/2 Elan TrackPoint".to_string(),
            enabled: None,
            button_map: Some(vec![1, 0, 3, 4, 5, 6, 7]),
            props: vec![(
                "libinput Accel Speed".to_string(),
                vec!["-0.200000".to_string()],
            )],
        }];

        let text = render_profile(&original);
        // Reuse the parser by feeding it the rendered text directly.
        let mut parsed: Vec<XSetting> = Vec::new();
        for line in text.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let Some((key, rest)) = line.split_once('=') else {
                continue;
            };
            match key.trim() {
                "device" => parsed.push(XSetting {
                    device: rest.trim().to_string(),
                    enabled: None,
                    button_map: None,
                    props: Vec::new(),
                }),
                "button-map" => {
                    parsed.last_mut().unwrap().button_map = Some(
                        rest.split_whitespace()
                            .map(|t| t.parse::<u8>().unwrap())
                            .collect(),
                    )
                }
                "prop" => {
                    let (name, values) = rest.split_once('=').unwrap();
                    parsed.last_mut().unwrap().props.push((
                        name.trim().to_string(),
                        values.split_whitespace().map(|s| s.to_string()).collect(),
                    ));
                }
                _ => {}
            }
        }

        assert_eq!(parsed.len(), 1);
        assert_eq!(parsed[0].device, "TPPS/2 Elan TrackPoint");
        assert_eq!(parsed[0].button_map, Some(vec![1, 0, 3, 4, 5, 6, 7]));
        assert_eq!(parsed[0].props[0].0, "libinput Accel Speed");
    }

    #[test]
    fn a_disabled_device_is_written_to_the_profile() {
        let text = render_profile(&[XSetting {
            device: "SynPS/2 Synaptics TouchPad".to_string(),
            enabled: Some(false),
            button_map: None,
            props: Vec::new(),
        }]);
        assert!(text.contains("device = SynPS/2 Synaptics TouchPad"));
        assert!(text.contains("enabled = 0"));
    }

    #[test]
    fn a_device_with_nothing_customised_is_omitted() {
        let text = render_profile(&[XSetting {
            device: "Some Mouse".to_string(),
            enabled: None,
            button_map: None,
            props: Vec::new(),
        }]);
        assert!(!text.contains("Some Mouse"));
    }

    #[test]
    fn a_property_name_with_spaces_stays_intact() {
        let text = render_profile(&[XSetting {
            device: "Some Mouse".to_string(),
            enabled: None,
            button_map: None,
            props: vec![(
                "libinput Natural Scrolling Enabled".to_string(),
                vec!["1".to_string()],
            )],
        }]);
        assert!(text.contains("prop = libinput Natural Scrolling Enabled = 1"));
    }
}
